name: Jenkins Integration

on:
 pull_request:
  push:
   branches: 
     - master
     - main
jobs:
  test:
    name: running unit tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger Jenkins
      uses: actions/jenkins-cli-action@v1
      with:
        jenkins-url: ${{ secrets.http://52.14.62.107:8080/ }}
        jenkins-user: ${{ secrets.admin }}
        jenkins-pass: ${{ secrets.admin }}
        command: build job/my-project -p git-branch=${{ https://github.com/saidusateesh/workflow.yml.git }}
