name: Jenkins Integration

on:
 pull_request:
  push:
   branches: 
     - master
     - main
jobs:
  test:
    name: running unit tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger Jenkins
      uses: actions/jenkins-cli-action@v1
      with:
        jenkins-url: ${{ secrets.JENKINS_URL }}
        jenkins-user: ${{ secrets.JENKINS_USERNAME }}
        jenkins-pass: ${{ secrets.JENKINS_PASSWORD }}
        command: build job/my-project -p git-branch=${{ github.ref }}
